name: flutter_fpt_socket
description: A Flutter socket chatbot plugin.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_fpt_socket
        pluginClass: FlutterFptSocketPlugin
      ios:
        pluginClass: FlutterFptSocketPlugin
